### ISSUE TITLE
The account is missing the "PFT_RS_REFRESH_TOKEN" credential. Please set it before continuing.

### ISSUE THREAD

**Issue by flaccid** [rs-services/rs-premium_free_trial#5]
```
$ export ACCOUNT_ID=1234
$ export SHARD_HOSTNAME=us-3.rightscale.com
$ export OAUTH_REFRESH_TOKEN=777205e6...9e229b5a
$ ./pftv2_bootstrap.sh
Checking for CAT_LIST_MODIFIER, used to replace the token CAT_LIST_MODIFIER in the pftv2_cat_list.txt file. Useful for alternate configs such as region specific mappings.
The environment variable CAT_LIST_MODIFIER was not set, so it will be set to 'default'.
### REQUIRED ### The account is missing the "PFT_RS_REFRESH_TOKEN" credential. Please set it before continuing.
$ echo "$?"
1
```

**Comment by flaccid** [comment]
Looks like we want the oauth token in explicitly named RS credential.

**Comment by rgeyer** [comment]
Is the error message not clear?

You're correct, we do need a credential pre-created which is named `PFT_RS_REFRESH_TOKEN`.

I had previously been creating or updating the credential using the `OAUTH_REFRESH_TOKEN` environment variable, however the credential must be a refresh token that is unique, and scoped to each account. The environment variable could be a refresh token for any account on the same shard.

**Comment by flaccid** [comment]
I guess, my little enhancement request is either doc in readme or/and when I go to do this:
```
$ ./pftv2_bootstrap.sh
The following environment variables must be set. OAUTH_REFRESH_TOKEN, ACCOUNT_ID, SHARD_HOSTNAME
```
It doesn't mention that requirement for `cred:PFT_RS_REFRESH_TOKEN`.

None of this is a great deal but I'm just trying to help it pass the 5 minute test.

**Comment by rgeyer** [comment]
The help output of the script refers to local environment variables which must be set in order to make API calls.

The "external" dependencies (Chef ST imported, and the cred created) have been in the README for some time.

https://github.com/rs-services/rs-premium_free_trial#prerequsites

**Comment by flaccid** [comment]
Fair point!
