### ISSUE TITLE
Chef Server for Linux (RightLink 10) [rev 10] is deprecated

### ISSUE THREAD

**Issue by flaccid** [rs-services/rs-premium_free_trial#6]
https://github.com/rs-services/rs-premium_free_trial/blob/master/pftv2_bootstrap.sh#L96

```
chef_server_response=$(rsc -r $OAUTH_REFRESH_TOKEN -a $ACCOUNT_ID -h $SHARD_HOSTNAME cm15 index server_templates "filter[]=name==Chef Server for Linux (RightLink 10)" "filter[]=revision==10")
```
Now at rev 14.

**Comment by rgeyer** [comment]
Correction.. Rev 15 (and anything above 10) is available only to internal sharing groups.

Rev 10 is the latest version publicly available.
